repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.6.0
    hooks:
      - id: ruff
        args: [--fix]
      - id: ruff-format
  - repo: https://github.com/mwouts/jupytext
    rev: v1.15.1
    hooks:
      - id: jupytext
        args: [--pre-commit]